<template>
  <div class="landing-page">
    <div class="hero-section">
      <h1>Login Practice</h1>
      <p class="hero-subtitle">
        Master your password manager with realistic login scenarios
      </p>
      <div class="hero-description">
        <p>
          Practice using your password manager with different login patterns to
          build confidence and muscle memory for real-world scenarios.
        </p>
      </div>
    </div>

    <div class="features-section">
      <h2>What You Can Practice</h2>
      <div class="features-grid">
        <div class="feature-card">
          <div class="feature-icon">👤</div>
          <h3>Create User Accounts</h3>
          <p>
            Set up test accounts with different usernames and passwords to
            practice with your password manager's save functionality.
          </p>
        </div>

        <div class="feature-card">
          <div class="feature-icon">🔐</div>
          <h3>1-Step Login</h3>
          <p>
            Practice logging in with username and password on a single screen,
            similar to most websites you encounter daily.
          </p>
        </div>

        <div class="feature-card">
          <div class="feature-icon">🔑</div>
          <h3>2-Step Login</h3>
          <p>
            Experience multi-step login flows where username and password are
            entered on separate screens, like some banking or enterprise sites.
          </p>
        </div>

        <div class="feature-card">
          <div class="feature-icon">⚙️</div>
          <h3>Account Management</h3>
          <p>
            View, edit, and manage your test accounts to practice updating
            credentials and managing your password manager's database.
          </p>
        </div>
      </div>
    </div>

    <div class="safety-section">
      <h2>Is This Safe?</h2>
      <div class="safety-content">
        <div class="safety-highlight">
          <div class="safety-icon">🛡️</div>
          <div class="safety-text">
            <h3>Your Data Never Leaves Your Computer</h3>
            <p>
              All user accounts, passwords, and login attempts are stored
              locally in your browser's localStorage. Nothing is sent to any
              external servers or databases.
            </p>
          </div>
        </div>

        <div class="safety-warning">
          <div class="warning-icon">⚠️</div>
          <div class="warning-text">
            <h3>Important Security Notice</h3>
            <p>
              <strong>Never use real passwords</strong> that you use elsewhere.
              This application is for practice only and should not be used with
              actual login credentials for any real services.
            </p>
            <ul class="warning-list">
              <li>Use only test passwords that you don't use anywhere else</li>
              <li>
                Don't use passwords for your email, banking, or social media
              </li>
              <li>
                Consider using random passwords generated by your password
                manager
              </li>
              <li>
                This is a learning tool, not a secure authentication system
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="getting-started-section">
      <h2>Getting Started</h2>
      <div class="steps">
        <div class="step">
          <div class="step-number">1</div>
          <div class="step-content">
            <h3>Create Test Users</h3>
            <p>
              Start by creating some test user accounts with fake credentials
              that you don't use anywhere else.
            </p>
          </div>
        </div>

        <div class="step">
          <div class="step-number">2</div>
          <div class="step-content">
            <h3>Practice Login Scenarios</h3>
            <p>
              Use the 1-Step and 2-Step login pages to practice with your
              password manager's autofill and save features.
            </p>
          </div>
        </div>

        <div class="step">
          <div class="step-number">3</div>
          <div class="step-content">
            <h3>Build Confidence</h3>
            <p>
              Repeat the process to build muscle memory and confidence in using
              your password manager effectively.
            </p>
          </div>
        </div>
      </div>

      <div class="cta-section">
        <router-link to="/create-user" class="cta-button">
          Start Practicing
        </router-link>
      </div>
    </div>

    <div class="footer-section">
      <p class="footer-text">
        This application is designed for educational purposes to help users
        become more comfortable with password managers. Always use unique, test
        passwords that you don't use elsewhere.
      </p>
    </div>
  </div>
</template>

<script>
export default {
  name: "LandingPage",
};
</script>

<style scoped>
.landing-page {
  max-width: 1000px;
  margin: 0 auto;
  padding: 2rem;
}

.hero-section {
  text-align: center;
  margin-bottom: 4rem;
  padding: 3rem 0;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  border-radius: 16px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);
}

h1 {
  font-size: 3rem;
  margin-bottom: 1rem;
  font-weight: 700;
}

.hero-subtitle {
  font-size: 1.5rem;
  margin-bottom: 1.5rem;
  opacity: 0.9;
  font-weight: 300;
}

.hero-description {
  max-width: 600px;
  margin: 0 auto;
}

.hero-description p {
  font-size: 1.1rem;
  line-height: 1.6;
  opacity: 0.95;
}

.features-section {
  margin-bottom: 4rem;
}

.features-section h2 {
  text-align: center;
  color: #333;
  margin-bottom: 3rem;
  font-size: 2.5rem;
}

.features-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 2rem;
}

.feature-card {
  background: white;
  padding: 2rem;
  border-radius: 12px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
  text-align: center;
  transition: transform 0.2s ease, box-shadow 0.2s ease;
}

.feature-card:hover {
  transform: translateY(-4px);
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.15);
}

.feature-icon {
  font-size: 3rem;
  margin-bottom: 1rem;
}

.feature-card h3 {
  color: #333;
  margin-bottom: 1rem;
  font-size: 1.25rem;
}

.feature-card p {
  color: #666;
  line-height: 1.6;
}

.safety-section {
  margin-bottom: 4rem;
  background: #f8f9fa;
  padding: 3rem;
  border-radius: 16px;
  border: 1px solid #e9ecef;
}

.safety-section h2 {
  text-align: center;
  color: #333;
  margin-bottom: 2rem;
  font-size: 2.5rem;
}

.safety-content {
  display: flex;
  flex-direction: column;
  gap: 2rem;
}

.safety-highlight {
  display: flex;
  align-items: flex-start;
  gap: 1.5rem;
  background: #d4edda;
  padding: 2rem;
  border-radius: 12px;
  border: 1px solid #c3e6cb;
}

.safety-icon {
  font-size: 2.5rem;
  flex-shrink: 0;
}

.safety-text h3 {
  color: #155724;
  margin-bottom: 0.5rem;
  font-size: 1.5rem;
}

.safety-text p {
  color: #155724;
  line-height: 1.6;
  margin: 0;
}

.safety-warning {
  display: flex;
  align-items: flex-start;
  gap: 1.5rem;
  background: #f8d7da;
  padding: 2rem;
  border-radius: 12px;
  border: 1px solid #f5c6cb;
}

.warning-icon {
  font-size: 2.5rem;
  flex-shrink: 0;
}

.warning-text h3 {
  color: #721c24;
  margin-bottom: 0.5rem;
  font-size: 1.5rem;
}

.warning-text p {
  color: #721c24;
  line-height: 1.6;
  margin-bottom: 1rem;
}

.warning-list {
  color: #721c24;
  margin: 0;
  padding-left: 1.5rem;
}

.warning-list li {
  margin-bottom: 0.5rem;
  line-height: 1.5;
}

.getting-started-section {
  margin-bottom: 4rem;
}

.getting-started-section h2 {
  text-align: center;
  color: #333;
  margin-bottom: 3rem;
  font-size: 2.5rem;
}

.steps {
  display: flex;
  flex-direction: column;
  gap: 2rem;
  margin-bottom: 3rem;
}

.step {
  display: flex;
  align-items: flex-start;
  gap: 1.5rem;
  background: white;
  padding: 2rem;
  border-radius: 12px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
}

.step-number {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  width: 3rem;
  height: 3rem;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 1.25rem;
  font-weight: 600;
  flex-shrink: 0;
}

.step-content h3 {
  color: #333;
  margin-bottom: 0.5rem;
  font-size: 1.25rem;
}

.step-content p {
  color: #666;
  line-height: 1.6;
  margin: 0;
}

.cta-section {
  text-align: center;
}

.cta-button {
  display: inline-block;
  background: linear-gradient(135deg, #28a745 0%, #20c997 100%);
  color: white;
  padding: 1rem 2rem;
  border-radius: 8px;
  text-decoration: none;
  font-size: 1.25rem;
  font-weight: 600;
  transition: transform 0.2s ease, box-shadow 0.2s ease;
}

.cta-button:hover {
  transform: translateY(-2px);
  box-shadow: 0 8px 24px rgba(40, 167, 69, 0.3);
}

.footer-section {
  text-align: center;
  padding: 2rem;
  background: #f8f9fa;
  border-radius: 12px;
  border: 1px solid #e9ecef;
}

.footer-text {
  color: #666;
  line-height: 1.6;
  margin: 0;
  font-size: 0.95rem;
}

@media (max-width: 768px) {
  .landing-page {
    padding: 1rem;
  }

  h1 {
    font-size: 2rem;
  }

  .hero-subtitle {
    font-size: 1.25rem;
  }

  .features-grid {
    grid-template-columns: 1fr;
  }

  .safety-highlight,
  .safety-warning {
    flex-direction: column;
    text-align: center;
  }

  .step {
    flex-direction: column;
    text-align: center;
  }

  .step-number {
    align-self: center;
  }
}
</style>
